# Generated by Django 4.2.8 on 2025-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
