# Generated by Django 4.2.20 on 2025-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
