# Generated by Django 4.2.20 on 2025-04-17 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 15, 2, 25, 881148, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
